
name: Configuration Secrets

patterns:
  - name: Hardcoded Spring SQL passwords
    description: |
      Hardcoded JDBC / Spring datasource passwords which typically are in property files or passed in at runtime
    type: hardcoded_spring_sql_passwords
    regex:
      version: 0.1
      pattern: |
        [a-zA-Z0-9!$%&*+?^_`{|}~-]+
      start: |
        [^0-9A-Za-z](spring.datasource.password|jdbc.password)(\s+|)=(\s+|)
      end: |
        \z|[^0-9A-Za-z]|'

    expected:
      - name: application.properties
        start_offset: 314
        end_offset: 318
      - name: application.properties
        start_offset: 358
        end_offset: 375
      - name: application.properties
        start_offset: 640
        end_offset: 646
      - name: application.properties
        start_offset: 874
        end_offset: 880
      - name: application.properties
        start_offset: 1141
        end_offset: 1147
      - name: application.properties
        start_offset: 1427
        end_offset: 1433

  - name: Django Secret Key
    type: django_secret_key
    regex:
      version: 0.1
      pattern: |
        [^\s"'(${{)][a-zA-Z0-9!.,$%&*+?^_`{|}()~-]*
      start: |
        [^0-9A-Za-z](SECRET_KEY)(\s+|)=(\s+|)("|')
      end: |
        \z|[^a-zA-Z0-9\s!.,$%&*+?^_`{|}()~-]|'|"

    comments:
      - "_If the secret is at the start of the file, its not picked up_"


  # Experimental

  - name: YAML Static Password Fields
    type: yaml_static_password_fields
    description: |
      Pattern to find Static passwords in YAML configuration files
    experimental: true
    regex:
      version: 0.1
      pattern: |
        [a-zA-Z0-9%!#$%&*+=?^_-{|}~\.,]{12,32}
      start: |
        [^0-9A-Za-z](\s+|)(secret|service_pass(wd|word|code|phrase)|pass(wd|word|code|phrase)|key)(\s+|):(\s+|)
      end: |
        [^0-9A-Za-z'"\(\)]|\z

    comments:
      - "The hardcoded password is between 12 and 32 chars long"
      - "Some false positives in Code might appear"
      - "The pattern only checks for cerain key words to begin the pattern (`secret:`, `password:`, etc.)"

    expected:
      - name: example.yml
        start_offset: 57
        end_offset: 80
      - name: example.yml
        start_offset: 57
        end_offset: 80

